services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - ${RECODE_OWUI_DATA_DIR}:/app/backend/data
      - ./custom_start.sh:/app/backend/custom_start.sh:ro
      - ./custom_start.py:/app/backend/custom_start.py:ro
      - ./recode_knowledge:/app/backend/recode_knowledge:ro
      - ./recode_electrophysiology_system_prompt.md:/app/backend/recode_electrophysiology_system_prompt.md:ro
      - ./recode_tri_logo.jpg:/app/backend/recode_tri_logo.jpg:ro
      - ./recode_models.json:/app/backend/recode_models.json:ro
      # Reference https://github.com/rndmcnlly/brace/blob/main/compose.yaml for the following:
      # - ./logo.svg:/app/backend/logo.svg:ro # TODO: use for splash etc...; place favicon in frontend 
      # - ./prompts.json:/app/backend/prompts.json:ro  # TODO: add predefined power-prompts like `/scenario`, `/proc`, etc based on common themes.
      # - ./functions:/functions:ro  # TODO: create directory of functions
      # - ./functions.json:/app/backend/functions.json:ro # TODO: present functions in the UI
      # - mount admin config here and load it
    entrypoint: ["bash", "/app/backend/custom_start.sh"]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      tika:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      ENV: ${ENV}
      WEBUI_NAME: ${WEBUI_NAME}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
  
      ENABLE_SIGNUP: ${ENABLE_SIGNUP}
      ENABLE_OAUTH_SIGNUP: ${ENABLE_OAUTH_SIGNUP}
      ENABLE_LOGIN_FORM: ${ENABLE_LOGIN_FORM}
      # OPENID_PROVIDER_URL: ${OPENID_PROVIDER_URL}
      # OPENID_REDIRECT_URI: ${OPENID_REDIRECT_URI}
      
      DEFAULT_USER_ROLE: ${DEFAULT_USER_ROLE}
      USER_PERMISSIONS_CHAT_DELETION: ${USER_PERMISSIONS_CHAT_DELETION}
      USER_PERMISSIONS_CHAT_EDITING: ${USER_PERMISSIONS_CHAT_EDITING}
      USER_PERMISSIONS_CHAT_TEMPORARY: ${USER_PERMISSIONS_CHAT_TEMPORARY}
      ENABLE_MESSAGE_RATING: ${ENABLE_MESSAGE_RATING}
      ENABLE_COMMUNITY_SHARING: ${ENABLE_COMMUNITY_SHARING}
      ENABLE_OLLAMA_API: ${ENABLE_OLLAMA_API}
      ENABLE_OPENAI_API: ${ENABLE_OPENAI_API}
      
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AUDIO_STT_ENGINE: ${AUDIO_STT_ENGINE}
      AUDIO_TTS_ENGINE: ${AUDIO_TTS_ENGINE}
      
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_POOL_SIZE: ${DATABASE_POOL_SIZE}
      DATABASE_POOL_MAX_OVERFLOW: ${DATABASE_POOL_MAX_OVERFLOW}
      DATABASE_POOL_TIMEOUT: ${DATABASE_POOL_TIMEOUT}

      CONTENT_EXTRACTION_ENGINE: ${CONTENT_EXTRACTION_ENGINE}
      
      VECTOR_DB: ${VECTOR_DB}
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
      RAG_EMBEDDING_ENGINE: ${RAG_EMBEDDING_ENGINE} 
      RAG_EMBEDDING_MODEL: ${RAG_EMBEDDING_MODEL}
      
      ENABLE_MODEL_FILTER: ${ENABLE_MODEL_FILTER}
      MODEL_FILTER_LIST: ${MODEL_FILTER_LIST}
      DEFAULT_MODELS: ${DEFAULT_MODELS}
      RESET_CONFIG_ON_START: ${RESET_CONFIG_ON_START}
      
      WEBSOCKET_MANAGER: ${WEBSOCKET_MANAGER}
      WEBSOCKET_REDIS_URL: ${WEBSOCKET_REDIS_URL}

    restart: unless-stopped

  # External Postgres database for all data storage and user management.
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${RECODE_POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recode-db"]
      interval: 1s
      timeout: 5s
      retries: 10

  # Postgres Admin Dashboard.
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED}
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  # Redis for caching and websocket manager.
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: always

  # Vector database.
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    volumes:
      - qdrant-data:/qdrant/storage

  # Apache Tika for extracting text from files.
  tika:
    image: apache/tika:latest-full
    container_name: apache-tika
    restart: always

volumes:
  redis-data: {}
  qdrant-data: {}
  pgadmin-data: {}
