services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - 'WEBUI_SECRET_KEY='
      - 'WEBSOCKET_MANAGER=redis'
      - 'WEBSOCKET_REDIS_URL=redis://redis:6379/0'
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/app/backend/redis
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  open-webui: {}
  redis-data: {}
