services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:  # Config mount reference: https://github.com/rndmcnlly/brace/blob/main/compose.yaml 
      - open-webui:/app/backend/data

    entrypoint: ["bash", "/app/backend/start.sh"]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      tika:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      ENV: prod
      WEBUI_NAME: ReCODE Chat
      WEBUI_FAVICON_URL: https://recodemedical.com/wp-content/uploads/2025/03/logo.svg
      WEBUI_SECRET_KEY: 
      
      ENABLE_SIGNUP: "false"
      ENABLE_OAUTH_SIGNUP: true
      ENABLE_LOGIN_FORM: "false"
      
      ENABLE_USAGE_LIMITS: "false"
      ENABLE_VERSION_UPDATE_CHECK: "false"
      OAUTH_CLIENT_ID: ${RECODE_OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${RECODE_OAUTH_CLIENT_SECRET}
      OPENID_PROVIDER_URL: ${RECODE_OPENID_PROVIDER_URL}
      OPENID_REDIRECT_URI: ${RECODE_OPENID_REDIRECT_URI}
      # OPENID_REDIRECT_URI: http://localhost:8080/oauth/oidc/callback  # For development
      
      DEFAULT_USER_ROLE: user
      USER_PERMISSIONS_CHAT_DELETION: "false"
      USER_PERMISSIONS_CHAT_EDITING: "false"
      USER_PERMISSIONS_CHAT_TEMPORARY: "false"
      ENABLE_MESSAGE_RATING: true
      ENABLE_COMMUNITY_SHARING: "false"
      ENABLE_OLLAMA_API: "false"
      ENABLE_OPENAI_API: true
      
      OPENAI_API_KEY: ${RECODE_OPENAI_API_KEY}
      RAG_OPENAI_API_KEY: ${RECODE_OPENAI_API_KEY}
      AUDIO_STT_OPENAI_API_KEY: ${RECODE_OPENAI_API_KEY}
      AUDIO_TTS_OPENAI_API_KEY: ${RECODE_OPENAI_API_KEY}
      AUDIO_STT_ENGINE: openai
      AUDIO_TTS_ENGINE: openai
      
      DATABASE_URL: ${RECODE_DATABASE_URI}
      SUPABASE_DATABASE_URL: ${RECODE_SUPABASE_DATABASE_URI}

      DATABASE_POOL_SIZE: 10
      DATABASE_POOL_MAX_OVERFLOW: 20
      DATABASE_POOL_TIMEOUT: 30

      CONTENT_EXTRACTION_ENGINE: tika
      
      # VECTOR_DB: qdrant
      # QDRANT_HOST: qdrant
      # QDRANT_PORT: 6333

      VECTOR_DB: qdrant
      QDRANT_URI: http://qdrant:6333  # This replaces QDRANT_HOST/QDRANT_PORT
      QDRANT_API_KEY: ""  # Leave empty if no auth needed, or set if you configure auth
      QDRANT_COLLECTION_PREFIX: "recode"  # Optional prefix for your collections
      QDRANT_ON_DISK: "true"  # Store vectors on disk for persistence
      QDRANT_PREFER_GRPC: "false"  # Use HTTP instead of gRPC for simplicity
      QDRANT_GRPC_PORT: 6334  # Only needed if PREFER_GRPC is true
      QDRANT_TIMEOUT: 30  # Timeout in seconds
      QDRANT_HNSW_M: 16  # HNSW algorithm parameter for performance tuning
      ENABLE_QDRANT_MULTITENANCY_MODE: "true"

      RAG_EMBEDDING_ENGINE: openai
      RAG_EMBEDDING_MODEL: text-embedding-3-large
      RAG_EMBEDDING_OPENAI_BATCH_SIZE: 2048
      
      ENABLE_MODEL_FILTER: true
      RESET_CONFIG_ON_START: "false"
      
      WEBSOCKET_MANAGER: redis
      WEBSOCKET_REDIS_URL: redis://redis:6379/0

    restart: unless-stopped

  # External Postgres database for all data storage and user management.
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${RECODE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${RECODE_POSTGRES_PASSWORD}
      POSTGRES_DB: recode-db
    volumes:
      - postgres-data:/var/lib/postgresql/data  # TODO: map to external dir so data is not lost and more space is available
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recode-db"]
      interval: 1s
      timeout: 5s
      retries: 10

  # Postgres Admin Dashboard.
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${RECODE_PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${RECODE_PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "True"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  # Redis for caching and websocket manager.
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: always

  # Vector database.
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    volumes:
      - qdrant-data:/qdrant/storage

  # Apache Tika for extracting text from files.
  tika:
    image: apache/tika:latest-full
    container_name: apache-tika
    restart: always

volumes:
  open-webui: {}
  redis-data: {}
  postgres-data: {}
  pgadmin-data: {}
  qdrant-data: {}
